---
title: "bathymap-for-amalga"
output: html_notebook
---

24 Feb 2022

## in ggplot

https://stackoverflow.com/questions/33227182/how-to-set-use-ggplot2-to-map-a-raster

```{r}
library(tidyverse)
library(ggplot2)
library(raster)
library(rasterVis)
library(rgdal)
library(grid)
library(scales)
library(viridis)  # better colors for everyone
library(ggthemes) # theme_map()
library(patchwork)
library(ggnewscale)
library(rnaturalearthdata)
library(rnaturalearth)
library(ggspatial)
library(ggOceanMaps)

```

```{r}
datafold <- "../data/JuneauBathy.tif"
test <- raster(datafold) 

# need to assign a CRS to the raster
# +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0
# is the CRS from the world map used for AK/GOA

crs(test) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
```


```{r}
test_spdf <- as(test, "SpatialPixelsDataFrame")
test_df <- as.data.frame(test_spdf)
colnames(test_df) <- c("depth", "x", "y")

zoom.df <- test_df %>%
  filter(x > -134.95, x < -134.76, y > 58.4, y < 58.55)
  #filter(x > -135, x < -134, y > 58.2, y < 58.7) 

zoom.df.w.gray <- zoom.df %>%
  mutate(depth = ifelse(depth >=0, NA, depth)) # set land to NA to shade it gray

# fully zoomed out
full_size_raster <- test_df %>%
  mutate(depth = ifelse(depth >=0, NA, depth)) # set land to NA to shade it gray
```


```{r add-transect-line}
# read in the data
# this dataframe is produced in the CTD analysis on the VM
# 08-ctd-cast-data.Rmd
ctd <- read_csv("../data/ctdDataframe.csv")

# just one of the transects (not both AM and PM)
am <- ctd %>%
  filter(tide == "AM_incoming") %>%
  dplyr::select(lat, long, id, distance) %>%
  unique() %>%
  filter(id != 1)

am %>%
  ggplot(aes(x = long, y = lat, label = id)) +
  geom_text()
```
```{r}
# minimum transect depth
# lat = 58.49468	
# long = -134.7925	

test_df %>%
  filter(x < -134.79, x > -134.793, y < 58.4948, y > 58.4946)

```


```{r zoom-for-mapping-amalga}
# filter the raster dataframe to zoom in on Amalga
highest.res <- test_df %>%
  filter(x > -134.83, x < -134.779, y > 58.47, y < 58.51) %>%
  mutate(depth = ifelse(depth >=0, NA, depth))  %>% # set land to NA to shade it gray
  mutate(depth = -1*depth) # flip the sign on depth values

highest.res
```
```{r}
# maximum value below sea level
tmp1 <- highest.res %>%
  filter(!is.na(depth))
 max.depth <- max(tmp1$depth)

# Break points sequence for below sea level
s1 <- seq(from=0, to=max.depth, by= max.depth / 15)

depth.scale <- round(s1, 0)
depth.scale <- unique(depth.scale)

depth.scale
breaks = levels(depth.scale)[floor(seq(1, nlevels(depth.scale), length.out = 10))]

new.depth.scale <- depth.scale[seq(1, length(depth.scale), 3)]
```

```{r zoom-plot}
highest.zoom.plot <- ggplot() +  
  geom_tile(data=highest.res, aes(x=x, y=y, fill = depth, color = depth)) + 
  scale_fill_steps2(high = "navyblue",
                    mid = "dodgerblue4",
  low = "lightsteelblue1",
  midpoint = 90,
  space = "Lab",
  na.value = "grey50",
  breaks = depth.scale) +
  scale_color_steps2(high = "navyblue",
                    mid = "dodgerblue4",
  low = "lightsteelblue1",
  midpoint = 90,
  na.value = "grey50",
  breaks = depth.scale) +
  coord_equal() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 8),
        axis.title.x = element_text(size = 10, margin = margin(t=10)),
        axis.title.y = element_text(size = 10, margin = margin(r=10)),
        axis.line = element_line(color = "gray50"),
        legend.position="right") +
       theme(legend.text = element_text(size = 6)) + 
      # theme(legend.key.height=unit(1, "cm")) +
      labs(fill = "Depth (m)",
         x = " ",
         y = " ") +
  guides(color = F) +
  scale_y_continuous(expand = c(0,0), breaks = c(58.48, 58.49, 58.50), labels = c("58.48°N", "58.49°N", "58.50°N")) +
  scale_x_continuous(expand = c(0,0), breaks = c(-134.82, -134.80, -134.78), labels = c("134.82°W", "134.80°W", "134.78°W")) # add labels for W and N
  

highest.zoom.plot
```


```{r plot-for-manuscript}
transect2021 <- highest.zoom.plot +
  geom_point(data = am, aes(x = long, y = lat), size = 1, color = "red") +
  #annotate(geom = "label", x = -134.795, y = 58.504, label = "Amalga Harbor", size = 4) +
  #annotate(geom = "label", x = -134.81, y = 58.494, label = "2021 transect", size = 3, fontface = "bold") +
  annotate(geom = "label", x = -134.78999, y = 58.496, label = "pens", size = 3, color = "black") +
    annotate(geom = "label", x = -134.808, y = 58.492, label = "1000m", size = 3, color = "black") +
      annotate(geom = "label", x = -134.825, y = 58.485, label = "2000m", size = 3, color = "black") +
  scale_x_continuous(limits = c(-134.83, -134.78), breaks = c(-134.82, -134.80, -134.78)) +
    scale_y_continuous(limits = c(58.47, 58.51)) 

```
at 560 m, it's basically the edge of Amalga Harbor.


For the 2022 data, I need the equivalent from the CTD casts for the transect.

#### CTD data from 2022


```{r read-in-data-from-2022}
ctd.2022 <- read_csv("../data/2022ctdDataframe.csv")

# grab the data for May 5 and one tide for data points for the map
one.set.2022 <- ctd.2022 %>%
  filter(str_detect(time, "2022-05-05") &
    tide == "AM_outgoing") %>%
  dplyr::select(ctd_sample, lat, long) %>%
  unique() %>%
  filter(!ctd_sample %in% c("163024", "191935", "175337", "185047")) %>%
  mutate(Year = "2022")

fp <- am %>%
  mutate(Year = "2021") %>%
  bind_rows(one.set.2022)

```

```{r intermed-bathy-map-for-panel}
amalga <- data.frame(lon = -134.80,
                     lat = 58.495)
#                      
# if only I could figure out how to annotate a ggoceanmap                   
interm_p <- basemap(limits = c(-138, -132, 56, 59), bathymetry = T, bathy.style = "rcb", rotate = T) +
  ggspatial::geom_spatial_point(data = amalga, aes(x = lon, y = lat), color = "red", size = 2) +
  labs(x = " ",
       y = " ") +
  theme(plot.margin = margin(r = 0.1, l = 0.1, t = 0.5, b = 0.5, unit = "cm")
    
  )
  
```


```{r}
amalga_plot2 <- highest.zoom.plot +
  #scale_x_continuous(limits = c(-134.825, -134.785)) +
  new_scale_color() +
  geom_point(data = fp, aes(x = long, y = lat, shape = Year, color = Year), size = 1.5) +
  annotate(geom = "label", x = -134.78999, y = 58.496, label = "pens", size = 3, color = "black") +
    annotate(geom = "label", x = -134.808, y = 58.4865, label = "1000m", size = 3, color = "black") +
      annotate(geom = "label", x = -134.826, y = 58.485, label = "2000m", size = 3, color = "black") +
        annotate(geom = "text", x = -134.805, y = 58.473, label = "Favorite Channel", size = 4, color = "white") +
          annotate(geom = "text", x = -134.80, y = 58.496, label = "Amalga Harbor", size = 4, color = "white") +
  scale_color_manual(values = c("coral3", "gold")) +
  scale_shape_manual(values = c(16,17)) +
  theme(
    legend.key = element_rect(fill = "white"),
    legend.box.spacing = unit(0.1, "cm")) +
  guides(color = guide_legend(override.aes = list(size = 5))) +
    annotation_north_arrow(location = "bl", which_north = "true", 
        pad_x = unit(0.5, "cm"), pad_y = unit(0.8, "cm"),
        height = unit(0.8, "cm"), width = unit(0.8, "cm"),
        style = north_arrow_orienteering(fill = c("black", "white")))


amalga_plot2
```

```{r context-map-pacific}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

ak_plot <- ggplot(data = world) +
  geom_sf() +
  theme(panel.background=element_rect(fill = 'aliceblue')) +
  coord_sf(xlim = c(-175, -125), ylim = c(45, 65), expand = F) +
  scale_y_continuous(breaks = c(45,55,65)) +
  annotate("rect", xmin = -137, xmax = -132, ymin = 56, ymax = 59, color = "red", fill = NA) +
  annotate("text", x = -155, y = 50, label = "Pacific Ocean", color = "gray20", size = 3.5) +
   annotate("text", x = -145, y = 57, label = "Gulf of\nAlaska", color = "gray20", size = 3) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = margin(r = 0.1, l = 0.1, t = 0.5, b = 0.5, unit = "cm")
  ) +
  annotation_scale(location = "bl", 
                  bar_cols = c("gray50","white"),
                  line_width = 0.4,
                  height = unit(0.2, "cm"),
                  pad_x = unit(0.25, "cm"),
                  pad_y = unit(0.25, "cm"),
                  text_pad = unit(0.15, "cm"))

ak_plot
```



Combine the ak plot and the Amalga plot
```{r multi-panel-plot-for-figure1}
# make Figure 1
(ak_plot | interm_p) / amalga_plot2 + plot_layout(nrow = 2, heights = c(2,3)) +
  plot_annotation(tag_levels = 'A') &
  theme(plot.tag = element_text(size = 8),
        plot.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"))

ggsave("pdf_outputs/amalga_combined_maps.png", width = 7, height = 7)

```




ß